"""empty message

Revision ID: 1f7e512118ac
Revises: 563468bec360
Create Date: 2024-01-05 19:34:56.225889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7e512118ac'
down_revision = '563468bec360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direcccion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pais', ['id_pais'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direcccion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
