"""empty message

Revision ID: 460516ac14a7
Revises: 17fa1340ddcc
Create Date: 2024-01-10 20:45:26.480163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460516ac14a7'
down_revision = '17fa1340ddcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_constraint('persona_dv_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.create_unique_constraint('persona_dv_key', ['dv'])

    # ### end Alembic commands ###
