"""empty message

Revision ID: 4f6662eac7b3
Revises: 1f7e512118ac
Create Date: 2024-01-05 23:22:52.106991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6662eac7b3'
down_revision = '1f7e512118ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('depto_casa', sa.String(length=10), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], ),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('direcccion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcccion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_pais', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_region', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('depto_casa', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('id_unidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], name='direcccion_id_pais_fkey'),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad.id'], name='direcccion_id_unidad_fkey'),
    sa.PrimaryKeyConstraint('id', name='direcccion_pkey')
    )
    op.drop_table('direccion')
    # ### end Alembic commands ###
