"""empty message

Revision ID: 563468bec360
Revises: 
Create Date: 2024-01-05 19:29:52.640275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563468bec360'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_iso', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_iso')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direcccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('depto_casa', sa.String(length=10), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factura', sa.String(length=100), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('monto_original', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura')
    )
    op.create_table('persona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil.id'], ),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comuna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_persona',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('monto_prorrateado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_gasto'], ['gasto.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id_persona', 'id_gasto')
    )
    op.create_table('tarea_persona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_termino', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tarea.id'], ),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarea_persona')
    op.drop_table('gasto_persona')
    op.drop_table('comuna')
    op.drop_table('tarea')
    op.drop_table('region')
    op.drop_table('persona')
    op.drop_table('gasto')
    op.drop_table('direcccion')
    op.drop_table('unidad')
    op.drop_table('perfil')
    op.drop_table('pais')
    # ### end Alembic commands ###
