"""empty message

Revision ID: 67e4c766efa9
Revises: 4f6662eac7b3
Create Date: 2024-01-08 17:31:21.489121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e4c766efa9'
down_revision = '4f6662eac7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_comuna', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'region', ['id_region'], ['id'])
        batch_op.create_foreign_key(None, 'comuna', ['id_comuna'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_comuna')

    # ### end Alembic commands ###
